In [1]:
import pandas as pd
import numpy as np
import pickle
from datasets import load_dataset


/home/f20222001/test-venv/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
with open('/home/f20222001/test-venv/UHI/Datasets_processed/inputs_36_v_clean_10k.pkl', 'rb') as f, open('/home/f20222001/test-venv/UHI/Datasets_processed/targets_36_v_clean_10k.pkl','rb') as t:
    inputs = pickle.load(f)
    targets = pickle.load(t)


In [3]:
inputs.shape

(738094, 36, 17)

In [6]:
t=inputs[0][0]
t

array([28.269766  , -0.19945148, -0.43699145,  0.03377805,  0.5       ,
        0.8660254 ,  1.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)

In [8]:
s=inputs[0]

In [ ]:
temp_dict={}
targets=t[0:4]
pos=t[4:7]
p= np.where(t[7:-1] == 1)[0][0]
print(p)

2


In [30]:
s[:,6]

array([ 1.,  4.,  5., 10., 15., 16., 25., 26., 27., 28., 38., 40., 41.,
       48., 49., 50., 52., 58., 59., 60., 61., 62., 63., 64., 65., 72.,
       73., 77., 82., 84., 85., 87., 88., 94., 95., 97.], dtype=float32)

In [39]:
s[:,6]

array([ 1.,  4.,  5., 10., 15., 16., 25., 26., 27., 28., 38., 40., 41.,
       48., 49., 50., 52., 58., 59., 60., 61., 62., 63., 64., 65., 72.,
       73., 77., 82., 84., 85., 87., 88., 94., 95., 97.], dtype=float32)

In [33]:
for ele in s:
    sin_val=ele[4]
    cos_val=ele[5]
    theta = np.arctan2(sin_val, cos_val)  # Recover angle
    theta = theta % (2 * np.pi)  # Ensure angle is in [0, 2pi)

    month_fraction = (12 * theta) / (2 * np.pi)
    month = int(round(month_fraction)) 

    # Wrap-around correction (if it becomes 13)
    if month > 12:
        month -= 12

    print(f"Recovered month: {month}")

Recovered month: 1
Recovered month: 4
Recovered month: 5
Recovered month: 10
Recovered month: 3
Recovered month: 4
Recovered month: 1
Recovered month: 2
Recovered month: 3
Recovered month: 4
Recovered month: 2
Recovered month: 4
Recovered month: 5
Recovered month: 12
Recovered month: 1
Recovered month: 2
Recovered month: 4
Recovered month: 10
Recovered month: 11
Recovered month: 12
Recovered month: 1
Recovered month: 2
Recovered month: 3
Recovered month: 4
Recovered month: 5
Recovered month: 12
Recovered month: 1
Recovered month: 5
Recovered month: 10
Recovered month: 12
Recovered month: 1
Recovered month: 3
Recovered month: 4
Recovered month: 10
Recovered month: 11
Recovered month: 1


In [27]:
targets[0]

np.float32(28.269766)

In [ ]:
def row_to_dict(s,w):
    past_values=[]
    past_time_features=[]
    static_cat=np.where(s[0][7:-1] == 1)[0][0]
    for ele in s:
        past_values.append(ele[0:4])
        past_time_features.append(ele[4:7])
    f_sin=
    s_dict={"past_values":past_values, "past_time_features":past_time_features, "static_cat":static_cat, "future_value":w}
    return s_dict


(36, 4)
